#!/bin/bash

set -euo pipefail

samplefile=/path/to/samples.txt

[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

#If fastqs are in a local file then additional argument:
#--local /path/to/fastq/dir \

nextflow run cellgeni/nf-starsolo \
  -entry strtseq \
  --samplefile $samplefile \
  --ansi-log false \
  -resume
