#!/bin/bash

set -euo pipefail

samplefile=/nfs/cellgeni/tickets/tic-2036/actions/sample.list1
config=/nfs/cellgeni/tickets/tic-2036/actions/nextflow.config

[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

nextflow run /nfs/cellgeni/tickets/tic-2036/actions/main.nf \
  --SAMPLEFILE $samplefile \
  --outdir /lustre/scratch126/cellgen/cellgeni/tickets/tic-2036/results \
  -c $config \
  --keep_bams true \
  -w starsolo-work \
  --ansi-log false \
  -resume
